# Generated by Django 5.1.2 on 2024-10-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviedata',
            options={'verbose_name': 'Moviedata', 'verbose_name_plural': 'Moviedata'},
        ),
        migrations.AddField(
            model_name='moviedata',
            name='genre',
            field=models.CharField(default='action', max_length=100),
        ),
    ]
